# model params
backbone:

image_size: 112



# run params
batch_size: 16

valid_num: 256          # half pos and half neg
valid_batch_size: 16
thresh: 0.2
below_fpr: 0.001        # fpr should below this
# paths

train_dir: '~/data/insightface/retinaface/train'
valid_dir: '~/data/insightface/retinaface/val'
test_dir: '~/data/insightface/retinaface/test'
ckpt_dir: '~/models/insightface/retinaface'
summary_dir: '~/logs/insightface/retinaface/summary'