# model params
backbone:

image_size: 640
num_class: 2
anchor_per_layer: 2


# run params
batch_size: 16


# paths

train_dir: '~/data/insightface/retinaface/train'
valid_dir: '~/data/insightface/retinaface/val'
test_dir: '~/data/insightface/retinaface/test'
ckpt_dir: '~/models/insightface/retinaface'
summary_dir: '~/logs/insightface/retinaface/summary'