# model params
backbone:

image_size: 112
embedding_size: 512



# hyper params

logits_scale: 64.0
logits_margin1: 0.5   # m1控制sphereface
logits_margin2: 0.5   # m2控制cosineface
logits_margin3: 0.5   # m3控制arcface


# run params

batch_size: 16
epoch_num: 20

valid_num: 256          # half pos and half neg
valid_batch_size: 16
thresh: 0.2
# paths

train_dir: '~/data/insightface/train'
valid_dir: '~/data/insightface/val'
test_dir:
ckpt_dir: '~/models/insightface/'
summary_dir: '~/logs/insightface/summary'